### ISSUE TITLE
redirect not working!!!!  WHYYY??????

### ISSUE THREAD

**Issue by MeredithS** [MeredithS/alimenting_with_ailments#3]
Hi Phil,

I hope you creep my reep real soon.

My issue is that when my users log-in they should be redirected to the /index page but it's not doing that for some reason.  I know the passwords match and everything is ok because when put  location.href="http://127.0.0.1:3000/index" into the controller and it works and my "in session" console logs

This is the section of code that is not working:

``` js
app.post('/login',function(req,res){
  authenticateUser(req.body.e_mail, req.body.password, function(user){
    if(user){
      req.session.name = user.first_name;
      req.session.userID = user._id;
      console.log('in session'); 
      res.redirect('/index');//could not figure out why this wouldn't work
    }
  });
})
```

This code is in my app.js Please help!

**Comment by phlco** [comment]
Rather than console.logging "in session" try console.logging more information from the request. does authenticateUser give errors?

**Comment by MeredithS** [comment]
@phlco  Hi Phil,
I actually already have a console.log in authenticateUser function as well.  It console.logs if the passwords match.  Which it is doing. ie it's not throwing an error.

**Comment by MeredithS** [comment]
@phlco  OMG, I just read my comment.  I didn't mean for it to sound so saucy! sorry about that!

**Comment by phlco** [comment]
Formatting your comment because if you're gonna sauce me like that it's atrocious to not use code fencing and syntax highlighting!

**Comment by phlco** [comment]
Also, please clarify WHAT it's doing if it's not directing you to "/index"

**Comment by MeredithS** [comment]
@phlco oh Phil. it isn't leaving the page at all.  it is just staying on the root page like nothing happened. 

so basically if I am logged out and I type http://127.0.0.1:3000/index directly into the URL, the page redirects me to the root.  Which it is supposed to do.  But if I log in with my user name Merbear@gmail.com and password Fuzzy123 and then type http://127.0.0.1:3000/index directly to the url it brings me to the right page. For some reason it just won't redirect me when I hit the button to sign in.

**Comment by phlco** [comment]
You're ajaxin' that thang!
